### ISSUE TITLE
New mockup

### ISSUE THREAD

**Issue by slarson** [openworm/model_completion_dashboard#2]
Use the [starting point](https://docs.google.com/drawings/d/1PcAMyBLZR3Z98gb4BDTUKp9PMDWZJHo2fnlYAVpISmo/edit) diagram and make a new google drawing design that fits with your vision for the dashboard

**Comment by shubhsingh594** [comment]
I have thought of a few changes, and how the UI should look.
There are two pages to the dashboard, that should capture all of the details. 
[Home Page](https://docs.google.com/drawings/d/10LsPhFjVFSCXvjHzdkfq6mmUWj7VP593BmHwjjHiwcg/edit?usp=sharing) and [Channel Page](https://docs.google.com/drawings/d/1cv3VQ4uCGfjb9jN-UKkDOiPlXWK1U30jMSrXDpBd49Y/edit?usp=sharing)
