### ISSUE TITLE
Create basic NeuroML channel reader

### ISSUE THREAD

**Issue by slarson** [openworm/model_completion_dashboard#7]
Using the EGL-36.channel.nml and the example channel.nml files in the muscle model, write a reader for channel files that outputs the key parameter data.  

This will eventually be modified to populate your UI for showing the values in the channels

Check out [this example](https://github.com/NeuroML/pyNeuroML/blob/11a34b737df46ea68afa9c4a10b97f0736c12117/pyneuroml/analysis/NML2ChannelAnalysis.py#L292) to structure your code

**Comment by shubhsingh594** [comment]
[gen.py](https://github.com/openworm/model_completion_dashboard/commit/2d1b5494fc3c9e971c6251ed0a382b3d0c8b7db4#diff-3721f43e4393b9a5a9fc1db2c8ba3eb4)

**Comment by slarson** [comment]
Padraig added a function to help pull the metadata out of the channel: https://github.com/NeuroML/pyNeuroML/issues/39
